name: census_series
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - census=0.8.20
  - yaml=0.2.5
  - pyarrow=16.1.0
  - python-duckdb=0.10.3
  - pandas=2.2.2
  - numpy=1.23.4
  - pip=22.2.2
  - pip:
      - us==2.0.2
      - censusdis==1.1.9
      - ipykernel==6.23.3
      - hydra-core==1.3
      - snakemake==8.1.2