name: census_series
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - census=0.8.20
  - yaml=0.2.5
  - pyarrow=14.0.2
  - pip=22.2.2
  - pip:
      - us==2.0.2
      - censusdis
      - pandas==1.5.1
      - numpy==1.23.4
      - ipykernel==6.23.3
      - hydra-core==1.3
      - snakemake==8.1.2