defaults:
  - _self_
  - datapaths: datapaths
  - census: acs1 #acs5, sf1
 
geo_type: county # type=str, choices=['county', 'state', 'zcta'], help='Geography type')
api_key: ${oc.env:CENSUS_API_KEY} # type=str, default=os.environ['CENSUS_API_KEY'])

hydra:
  run:
    dir: logs/${now:%Y-%m-%d}/${now:%H-%M-%S}