defaults:
  - _self_
  - datapaths: datapaths
  - variable_codes: core

# logging config
hydra:
  run:
    dir: logs/${now:%Y-%m-%d}/${now:%H-%M-%S}


# minimal arguments
geo_type:  # 'zcta'  # type=Literal['zcta', 'county', 'state'], help='Geography type to fetch data for'
survey:  # type=Literal['dec', 'acs1', 'acs5'], help='Census survey to fetch data for'
variable:  # (e.g. variable=popultion) help='Census variable listed in a census yaml file'
api_key: ${oc.env:CENSUS_API_KEY} # type=str, default=os.environ['CENSUS_API_KEY'], help='Census API key'


# years available for each geography type and survey
valid_years:
  county:
    dec: [2000, 2010, 2020]
    acs5: [2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022]
    acs1: [2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2021, 2022]
  zcta:
    dec: [2000, 2010, 2020]
    acs5: [2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022]
